### PR TITLE
Updated with Volunteer Service

### PR DESCRIPTION
**Pull request by WaP2000**
Users can submit, cancel and view their volunteer applications

### CODE REVIEW

**Comment by WaP2000** [comment]
I removed some of the functionalities related to volunteer application from UsreService to a class called volunteerService

**Comment by Lulu54368** [comment]
Can you resolve the conflict first?

**Comment by WaP2000** [comment]
Ok, just a sec, let me resolve the conflict

**Comment by Lulu54368** [comment]
Already merged

**Pull request closed without merging**
